export enum SportType {
    Hike = 'Hike',
    Run = 'Run',
    Ride = 'Ride',
    Swim = 'Swim',
    Snowboard = 'Snowboard',
    AlpineSki = 'AlpineSki',
    // 'Skateboard',
    // 'BackcountrySki',
    // 'Canoeing',
    // 'Crossfit',
    // 'EBikeRide',
    // 'Elliptical',
    // 'EMountainBikeRide',
    // 'Golf',
    // 'GravelRide',
    // 'Handcycle',
    // 'IceSkate',
    // 'InlineSkate',
    // 'Kayaking',
    // 'Kitesurf',
    // 'MountainBikeRide',
    // 'NordicSki',
    // 'RockClimbing',
    // 'RollerSki',
    // 'Rowing',
    // 'Sail',
    // 'Snowshoe',
    // 'Soccer',
    // 'StairStepper',
    // 'StandUpPaddling',
    // 'Surfing',
    // 'TrailRun',
    // 'Velomobile',
    // 'VirtualRide',
    // 'VirtualRun',
    // 'Walk',
    // 'WeightTraining',
    // 'Wheelchair',
    // 'Windsurf',
    // 'Workout',
    // 'Yoga'
}
